spring.application.name = A3NgoLeMinhQuan_SE18D04
server.port = 8080
spring.datasource.driver-class-name =com.microsoft.sqlserver.jdbc.SQLServerDriver

spring.datasource.url = jdbc:sqlserver://localhost:1433;encrypt=true;trustServerCertificate=true;databaseName=A3NgoLeMinhQuan_SE18D04
spring.datasource.username = sa
spring.datasource.password = 123

staff.email = staff@gmail.com
staff.password = $2a$10$d7pfxpF/pzZZNn2Zz/trqeEpAVqfmg0xXyeOEb.7bH703y2QLOzta
staff.role = ROLE_STAFF

spring.jpa.database-platform = org.hibernate.dialect.SQLServerDialect
spring.jpa.hibernate.ddl-auto = update
spring.jpa.show-sql = true

security.jwt.secret = 3cfa7473746461234567890abcdef1234567890abcdef1234567890abcdef
security.jwt.expiration = 3600000

